sources:
    osm:
        type: TopoJSON
        url:  //vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-HqUVidw
        
camera:
    type: perspective
    vanishing_point: [0, -1000]

lights:
    light1:
        type: ambient
        direction: [1, 1, -.9]
        diffuse: .0
        ambient: 2.

styles:
    flatlines:
        base: lines
        lighting: false # ignore lights
    flatpolys:
        base: polygons
        lighting: false # ignore lights

    galaxy:
        base: polygons
        material:
            ambient:
                texture: galaxy.jpg
                mapping: spheremap
    stars:
        base: polygons
        material:
            ambient:
                texture: stars.jpg
                mapping: spheremap
                # scale: .0001

    # import noise function from external file
    noise:
        url: noise.yaml

    buildings:
        base: polygons
        mix: [galaxy, noise]
        animated: true
        shaders:
            defines:
                GRAIN_AMOUNT: .3
                NUM_OCTAVES: 1
            uniforms:
                u_frequency: 8.
            blocks:
                color: |
                    float pixelSize = 4.;
                    float fps = .05;
                    float t = u_time * fps;
                    float t2 = u_time * fps +.66;
                    vec3 pos = floor(v_world_position.xyz/pixelSize);
                    vec3 sparkles = vec3(0.);
                    sparkles = vec3(cnoise(pos+t))*2.;
                    sparkles += vec3(cnoise(pos+t2))*2.;
                    // clamp
                    float minInput = .95;
                    float maxInput = 1.;
                    sparkles = min(max(sparkles - vec3(minInput), vec3(0.0)) / (vec3(maxInput) - vec3(minInput)), vec3(1.0));
                    // brighten 
                    sparkles += .5;
                    color.rgb *= sparkles;
                    
    roads:
        base: lines
        texcoords: true
        blend: add
        shaders:
            blocks:
                color: |
                    vec2 st = v_texcoord.xy;
                    color.rgb = vec3(st.xy*.5, 1.);
    
layers:
    earth:
        data: { source: osm, layer: earth }
        draw:
            stars:
                order: 0
                color: [.1, .1, .1]

    landuse:
        data: { source: osm, layer: landuse }
        parks:
            draw:
                stars:
                    order: 1
                    color: white
    water:
        data: { source: osm, layer: water }
        draw:
            stars:
                order: 3
                color: [0.671, 0.784, 0.949]

    roads:
        data: { source: osm, layer: roads }
        filter: { not: {kind: [rail] } }
        draw:
            roads:
                order: 7
                color: white
                width: 10px
        highway:
            filter: { kind: highway }
            draw:
                roads:
                    color: white
                    width: 17px


    # buildings are the only layer that gets lighting
    buildings:
        data: { source: osm }
        draw:
            buildings:
                order: 80
                # color: |
                #     function () {
                #         var a = feature.area;
                #         var h = feature.height;
                #         var v = Math.floor(Math.random(1)*2)*.25;
                #         var r = feature.area > 10000 ? .5 : 0.;
                #         var g = feature.height > 150 ? .5 : 0.;
                #         var b = feature.height > 150 ? .5 : 0.;                        
                #         return [v+r, v+g, v];
                #         // return [v, v, v];
                #     }
                extrude: function () { return feature.height || feature.area / 100 % 1 * 20 + 20; }
        